# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none
pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/kubernetesruntime/ci.mgmt.yml
    - sdk/kubernetesruntime/Azure.ResourceManager.ContainerOrchestratorRuntime/


  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/kubernetesruntime/ci.mgmt.yml
    - sdk/kubernetesruntime/Azure.ResourceManager.ContainerOrchestratorRuntime/


  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/kubernetesruntime/ci.mgmt.yml
    - sdk/kubernetesruntime/Azure.ResourceManager.ContainerOrchestratorRuntime/


  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/kubernetesruntime/ci.mgmt.yml
    - sdk/kubernetesruntime/Azure.ResourceManager.ContainerOrchestratorRuntime/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: kubernetesruntime
    ArtifactName: packages
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.ContainerOrchestratorRuntime
      safeName: AzureResourceManagerContainerOrchestratorRuntime
