# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/SpeechToText
    - sdk/SpeechToText/ci.yml
    - sdk/SpeechToText/Azure.AI.Speech

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/SpeechToText
    - sdk/SpeechToText/ci.yml
    - sdk/SpeechToText/Azure.AI.Speech

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: SpeechToText
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.Speech
      safeName: AzureAISpeech
