# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/encode/ci.yml
    - sdk/encode/Encode.Array/
    - sdk/encode/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: encode
    ArtifactName: packages
    Artifacts:
    - name: Encode.Array
      safeName: EncodeArray