// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.CosmosDBForPostgreSql.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Authentication configuration of a cluster.
    /// </summary>
    public partial class AuthConfig
    {
        /// <summary>
        /// Initializes a new instance of the AuthConfig class.
        /// </summary>
        public AuthConfig()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AuthConfig class.
        /// </summary>
        /// <param name="activeDirectoryAuth">Possible values include:
        /// 'enabled', 'disabled'</param>
        /// <param name="passwordAuth">Possible values include: 'enabled',
        /// 'disabled'</param>
        public AuthConfig(string activeDirectoryAuth = default(string), string passwordAuth = default(string))
        {
            ActiveDirectoryAuth = activeDirectoryAuth;
            PasswordAuth = passwordAuth;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'enabled', 'disabled'
        /// </summary>
        [JsonProperty(PropertyName = "activeDirectoryAuth")]
        public string ActiveDirectoryAuth { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'enabled', 'disabled'
        /// </summary>
        [JsonProperty(PropertyName = "passwordAuth")]
        public string PasswordAuth { get; set; }

    }
}
