// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.CosmosDBForPostgreSql.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for Create operation.
    /// </summary>
    public partial class ClustersCreateHeaders
    {
        /// <summary>
        /// Initializes a new instance of the ClustersCreateHeaders class.
        /// </summary>
        public ClustersCreateHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClustersCreateHeaders class.
        /// </summary>
        public ClustersCreateHeaders(string location = default(string), string azureAsyncOperation = default(string))
        {
            Location = location;
            AzureAsyncOperation = azureAsyncOperation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "azure-async-operation")]
        public string AzureAsyncOperation { get; set; }

    }
}
