// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.CosmosDBForPostgreSql.Models
{

    /// <summary>
    /// Defines values for DataEncryptionType.
    /// </summary>
    public static class DataEncryptionType
    {
        public const string AzureKeyVault = "AzureKeyVault";
        public const string SystemAssigned = "SystemAssigned";
    }
}
