// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.CosmosDBForPostgreSql.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The data encryption properties of a cluster.
    /// </summary>
    public partial class DataEncryption
    {
        /// <summary>
        /// Initializes a new instance of the DataEncryption class.
        /// </summary>
        public DataEncryption()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataEncryption class.
        /// </summary>
        /// <param name="primaryKeyUri">URI for the key in keyvault for data
        /// encryption of the primary server.</param>
        /// <param name="primaryUserAssignedIdentityId">Resource Id for the
        /// User assigned identity to be used for data encryption of the
        /// primary server.</param>
        /// <param name="type">Possible values include: 'AzureKeyVault',
        /// 'SystemAssigned'</param>
        public DataEncryption(string primaryKeyUri = default(string), string primaryUserAssignedIdentityId = default(string), string type = default(string))
        {
            PrimaryKeyUri = primaryKeyUri;
            PrimaryUserAssignedIdentityId = primaryUserAssignedIdentityId;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets URI for the key in keyvault for data encryption of the
        /// primary server.
        /// </summary>
        [JsonProperty(PropertyName = "primaryKeyUri")]
        public string PrimaryKeyUri { get; set; }

        /// <summary>
        /// Gets or sets resource Id for the User assigned identity to be used
        /// for data encryption of the primary server.
        /// </summary>
        [JsonProperty(PropertyName = "primaryUserAssignedIdentityId")]
        public string PrimaryUserAssignedIdentityId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'AzureKeyVault',
        /// 'SystemAssigned'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
