// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.CosmosDBForPostgreSql.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Request from client to promote geo-redundant replica
    /// </summary>
    public partial class PromoteRequest
    {
        /// <summary>
        /// Initializes a new instance of the PromoteRequest class.
        /// </summary>
        public PromoteRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PromoteRequest class.
        /// </summary>
        /// <param name="enableGeoBackup">Boolean property to enable
        /// geo-redundant replica promotion.</param>
        public PromoteRequest(bool? enableGeoBackup = default(bool?))
        {
            EnableGeoBackup = enableGeoBackup;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets boolean property to enable geo-redundant replica
        /// promotion.
        /// </summary>
        [JsonProperty(PropertyName = "enableGeoBackup")]
        public bool? EnableGeoBackup { get; set; }

    }
}
