// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.CosmosDBForPostgreSql.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The name object for a server.
    /// </summary>
    public partial class ServerNameItem
    {
        /// <summary>
        /// Initializes a new instance of the ServerNameItem class.
        /// </summary>
        public ServerNameItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServerNameItem class.
        /// </summary>
        /// <param name="name">The name of a server.</param>
        /// <param name="fullyQualifiedDomainName">The fully qualified domain
        /// name of a server.</param>
        public ServerNameItem(string name = default(string), string fullyQualifiedDomainName = default(string))
        {
            Name = name;
            FullyQualifiedDomainName = fullyQualifiedDomainName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name of a server.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets the fully qualified domain name of a server.
        /// </summary>
        [JsonProperty(PropertyName = "fullyQualifiedDomainName")]
        public string FullyQualifiedDomainName { get; private set; }

    }
}
