# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/removed/ci.yml
    - sdk/removed/Versioning.Removed.V1/
    - sdk/removed/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: removed
    ArtifactName: packages
    Artifacts:
    - name: Versioning.Removed.V1
      safeName: VersioningRemovedV1