# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/naming/ci.yml
    - sdk/naming/Client.Naming.EnumConflict/
    - sdk/naming/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: naming
    ArtifactName: packages
    Artifacts:
    - name: Client.Naming.EnumConflict
      safeName: ClientNamingEnumConflict