# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/workloads
    - sdk/workloads/ci.yml
    - sdk/workloads/Azure.Workloads.SAPVirtualInstance

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/workloads
    - sdk/workloads/ci.yml
    - sdk/workloads/Azure.Workloads.SAPVirtualInstance

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: workloads
    ArtifactName: packages
    Artifacts:
    - name: Azure.Workloads.SAPVirtualInstance
      safeName: AzureWorkloadsSAPVirtualInstance
