# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/special-headers/ci.yml
    - sdk/special-headers/SpecialHeaders.ConditionalRequest/
    - sdk/special-headers/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: special-headers
    ArtifactName: packages
    Artifacts:
    - name: SpecialHeaders.ConditionalRequest
      safeName: SpecialHeadersConditionalRequest