# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/enum/ci.yml
    - sdk/enum/Type.Enum.Extensible/
    - sdk/enum/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: enum
    ArtifactName: packages
    Artifacts:
    - name: Type.Enum.Extensible
      safeName: TypeEnumExtensible