# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/parameters/ci.yml
    - sdk/parameters/Parameters.Basic/
    - sdk/parameters/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: parameters
    ArtifactName: packages
    Artifacts:
    - name: Parameters.Basic
      safeName: ParametersBasic