# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/model/ci.yml
    - sdk/model/Type.Model.Empty/
    - sdk/model/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: model
    ArtifactName: packages
    Artifacts:
    - name: Type.Model.Empty
      safeName: TypeModelEmpty