# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/azuresiterecovery/ci.mgmt.yml
    - sdk/azuresiterecovery/Azure.ResourceManager.Azuresiterecovery/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azuresiterecovery
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.Azuresiterecovery
      safeName: AzureResourceManagerAzuresiterecovery
