# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/inheritance/ci.yml
    - sdk/inheritance/Type.Model.Inheritance.EnumDiscriminator/
    - sdk/inheritance/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: inheritance
    ArtifactName: packages
    Artifacts:
    - name: Type.Model.Inheritance.EnumDiscriminator
      safeName: TypeModelInheritanceEnumDiscriminator