# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/service/ci.yml
    - sdk/service/Service.MultiService.Combined/
    - sdk/service/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: service
    ArtifactName: packages
    Artifacts:
    - name: Service.MultiService.Combined
      safeName: ServiceMultiServiceCombined