# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/endpoint/ci.yml
    - sdk/endpoint/Server.Endpoint.NotDefined/
    - sdk/endpoint/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: endpoint
    ArtifactName: packages
    Artifacts:
    - name: Server.Endpoint.NotDefined
      safeName: ServerEndpointNotDefined