# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/client-location/ci.yml
    - sdk/client-location/Specs.Azure.Tcgc.ClientLo.Param/
    - sdk/client-location/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: client-location
    ArtifactName: packages
    Artifacts:
    - name: Specs.Azure.Tcgc.ClientLo.Param
      safeName: SpecsAzureTcgcClientLoParam