# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/client-initialization/ci.yml
    - sdk/client-initialization/Specs.Azure.Tcgc.ClientInit.Default/
    - sdk/client-initialization/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: client-initialization
    ArtifactName: packages
    Artifacts:
    - name: Specs.Azure.Tcgc.ClientInit.Default
      safeName: SpecsAzureTcgcClientInitDefault