# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/analyzetext
    - sdk/analyzetext/ci.yml
    - sdk/analyzetext/Azure.AI.Language.Authoring.Analyzetext

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/analyzetext
    - sdk/analyzetext/ci.yml
    - sdk/analyzetext/Azure.AI.Language.Authoring.Analyzetext

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: analyzetext
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.Language.Authoring.Analyzetext
      safeName: AzureAILanguageAuthoringAnalyzetext
