# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/ai
    - sdk/ai/ci.yml
    - sdk/ai/Azure.AI.Projects1DP

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/ai
    - sdk/ai/ci.yml
    - sdk/ai/Azure.AI.Projects1DP

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: ai
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.Projects1DP
      safeName: AzureAIProjects1DP
