# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/programmableconnectivity
    - sdk/programmableconnectivity/ci.yml
    - sdk/programmableconnectivity/Azure.Communication.ProgrammableConnectivity

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/programmableconnectivity
    - sdk/programmableconnectivity/ci.yml
    - sdk/programmableconnectivity/Azure.Communication.ProgrammableConnectivity

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: programmableconnectivity
    ArtifactName: packages
    Artifacts:
    - name: Azure.Communication.ProgrammableConnectivity
      safeName: AzureCommunicationProgrammableConnectivity
