# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/structure/ci.yml
    - sdk/structure/Client.Structure.Service/
    - sdk/structure/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: structure
    ArtifactName: packages
    Artifacts:
    - name: Client.Structure.Service
      safeName: ClientStructureService