# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/previewVersion/ci.yml
    - sdk/previewVersion/Versioning.PreviewVersion.V1/
    - sdk/previewVersion/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: previewVersion
    ArtifactName: packages
    Artifacts:
    - name: Versioning.PreviewVersion.V1
      safeName: VersioningPreviewVersionV1