# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/api-version/ci.yml
    - sdk/api-version/_Specs_.Azure.ClientGenerator.Core.ApiVersion.Header/
    - sdk/api-version/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: api-version
    ArtifactName: packages
    Artifacts:
    - name: _Specs_.Azure.ClientGenerator.Core.ApiVersion.Header
      safeName: _Specs_AzureClientGeneratorCoreApiVersionHeader