# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/azurefleet/ci.mgmt.yml
    - sdk/azurefleet/Azure.ResourceManager.Azurefleet/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azurefleet
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.Azurefleet
      safeName: AzureResourceManagerAzurefleet
