# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/azurefleet
    - sdk/azurefleet/ci.yml
    - sdk/azurefleet/Azure.ResourceManager.ComputeFleet

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/azurefleet
    - sdk/azurefleet/ci.yml
    - sdk/azurefleet/Azure.ResourceManager.ComputeFleet

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azurefleet
    ArtifactName: packages
    Artifacts:
    - name: Azure.ResourceManager.ComputeFleet
      safeName: AzureResourceManagerComputeFleet
