# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/typeChangedFrom/ci.yml
    - sdk/typeChangedFrom/Versioning.TypeChangedFrom.V1/
    - sdk/typeChangedFrom/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: typeChangedFrom
    ArtifactName: packages
    Artifacts:
    - name: Versioning.TypeChangedFrom.V1
      safeName: VersioningTypeChangedFromV1