# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/payload/ci.yml
    - sdk/payload/Payload.ContentNegotiation/
    - sdk/payload/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: payload
    ArtifactName: packages
    Artifacts:
    - name: Payload.ContentNegotiation
      safeName: PayloadContentNegotiation