# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/example/ci.yml
    - sdk/example/_Specs_.Azure.Example.Basic/
    - sdk/example/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: example
    ArtifactName: packages
    Artifacts:
    - name: _Specs_.Azure.Example.Basic
      safeName: _Specs_AzureExampleBasic