
// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.CosmosDBForPostgreSql
{
  using System;
  using System.Collections.Generic;
  using System.Linq;

  internal static partial class SdkInfo
  {
      public static IEnumerable<Tuple<string, string, string>> ApiInfo_CosmosDBforPostgreSQL
      {
          get
          {
              return new Tuple<string, string, string>[]
              {
                new Tuple<string, string, string>("DBforPostgreSQL", "Clusters", "2023-03-02-preview"),
                new Tuple<string, string, string>("DBforPostgreSQL", "Configurations", "2023-03-02-preview"),
                new Tuple<string, string, string>("DBforPostgreSQL", "FirewallRules", "2023-03-02-preview"),
                new Tuple<string, string, string>("DBforPostgreSQL", "Operations", "2023-03-02-preview"),
                new Tuple<string, string, string>("DBforPostgreSQL", "PrivateEndpointConnections", "2023-03-02-preview"),
                new Tuple<string, string, string>("DBforPostgreSQL", "PrivateLinkResources", "2023-03-02-preview"),
                new Tuple<string, string, string>("DBforPostgreSQL", "Roles", "2023-03-02-preview"),
                new Tuple<string, string, string>("DBforPostgreSQL", "Servers", "2023-03-02-preview"),
              }.AsEnumerable();
          }
      }
  }
}
