# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/authentication/ci.yml
    - sdk/authentication/Authentication.ApiKey/
    - sdk/authentication/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: authentication
    ArtifactName: packages
    Artifacts:
    - name: Authentication.ApiKey
      safeName: AuthenticationApiKey