# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/http/ci.yml
    - sdk/http/Authentication.Http.Custom/
    - sdk/http/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: http
    ArtifactName: packages
    Artifacts:
    - name: Authentication.Http.Custom
      safeName: AuthenticationHttpCustom