# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/typespec-azure/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/typespec-azure/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: typespec-azure
    ArtifactName: packages
    Artifacts:
    - name: Azure.ApiManagement.DeveloperServicesAPI
      safeName: AzureApiManagementDeveloperServicesAPI
