# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/playwright
    - sdk/playwright/ci.yml
    - sdk/playwright/Azure.Developer.Playwright

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/playwright
    - sdk/playwright/ci.yml
    - sdk/playwright/Azure.Developer.Playwright

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: playwright
    ArtifactName: packages
    Artifacts:
    - name: Azure.Developer.Playwright
      safeName: AzureDeveloperPlaywright
