# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/deid
    - sdk/deid/ci.yml
    - sdk/deid/Azure.HealthDataAIServices.Deid

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/deid
    - sdk/deid/ci.yml
    - sdk/deid/Azure.HealthDataAIServices.Deid

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: deid
    ArtifactName: packages
    Artifacts:
    - name: Azure.HealthDataAIServices.Deid
      safeName: AzureHealthDataAIServicesDeid
