# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/edgeworkloadsecurity/ci.mgmt.yml
    - sdk/edgeworkloadsecurity/Azure.ResourceManager.SecretsStoreExtension/


extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: edgeworkloadsecurity
    ArtifactName: packages
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.SecretsStoreExtension
      safeName: AzureResourceManagerSecretsStoreExtension
