# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/returnTypeChangedFrom/ci.yml
    - sdk/returnTypeChangedFrom/Versioning.ReturnTypeChangedFrom.V1/
    - sdk/returnTypeChangedFrom/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: returnTypeChangedFrom
    ArtifactName: packages
    Artifacts:
    - name: Versioning.ReturnTypeChangedFrom.V1
      safeName: VersioningReturnTypeChangedFromV1