# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/path/ci.yml
    - sdk/path/Server.Path.Multiple/
    - sdk/path/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: path
    ArtifactName: packages
    Artifacts:
    - name: Server.Path.Multiple
      safeName: ServerPathMultiple