# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/renamedFrom/ci.yml
    - sdk/renamedFrom/Versioning.RenamedFrom.V1/
    - sdk/renamedFrom/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: renamedFrom
    ArtifactName: packages
    Artifacts:
    - name: Versioning.RenamedFrom.V1
      safeName: VersioningRenamedFromV1