# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/agricultureplatform
    - sdk/agricultureplatform/ci.yml
    - sdk/agricultureplatform/Azure.AgriculturePlatform

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/agricultureplatform
    - sdk/agricultureplatform/ci.yml
    - sdk/agricultureplatform/Azure.AgriculturePlatform

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: agricultureplatform
    ArtifactName: packages
    Artifacts:
    - name: Azure.AgriculturePlatform
      safeName: AzureAgriculturePlatform
