# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/messagingconnectors/ci.mgmt.yml
    - sdk/messagingconnectors/Azure.ResourceManager.Messagingconnectors/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: messagingconnectors
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.Messagingconnectors
      safeName: AzureResourceManagerMessagingconnectors
