# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/face
    - sdk/face/ci.yml
    - sdk/face/Azure.AI.Face

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/face
    - sdk/face/ci.yml
    - sdk/face/Azure.AI.Face

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: face
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.Face
      safeName: AzureAIFace
