# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/impact/ci.mgmt.yml
    - sdk/impact/Azure.ResourceManager.Impact/


extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: impact
    ArtifactName: packages
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.Impact
      safeName: AzureResourceManagerImpact
