# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/srv-driven/ci.yml
    - sdk/srv-driven/Resiliency.SrvDriven.V1/
    - sdk/srv-driven/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: srv-driven
    ArtifactName: packages
    Artifacts:
    - name: Resiliency.SrvDriven.V1
      safeName: ResiliencySrvDrivenV1