# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/iotoperations
    - sdk/iotoperations/ci.yml
    - sdk/iotoperations/Azure.ResourceManager.IoTOperations

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/iotoperations
    - sdk/iotoperations/ci.yml
    - sdk/iotoperations/Azure.ResourceManager.IoTOperations

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: iotoperations
    ArtifactName: packages
    Artifacts:
    - name: Azure.ResourceManager.IoTOperations
      safeName: AzureResourceManagerIoTOperations
