# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/versions/ci.yml
    - sdk/versions/Server.Versions.NotVersioned/
    - sdk/versions/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: versions
    ArtifactName: packages
    Artifacts:
    - name: Server.Versions.NotVersioned
      safeName: ServerVersionsNotVersioned