# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/contentsafetyinternal
    - sdk/contentsafetyinternal/ci.yml
    - sdk/contentsafetyinternal/Azure.AI.ContentSafetyInternal

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/contentsafetyinternal
    - sdk/contentsafetyinternal/ci.yml
    - sdk/contentsafetyinternal/Azure.AI.ContentSafetyInternal

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: contentsafetyinternal
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.ContentSafetyInternal
      safeName: AzureAIContentSafetyInternal
