# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/core/ci.yml
    - sdk/core/_Specs_.Azure.Core.Basic/
    - sdk/core/service.projects

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    SDKType: client
    ServiceDirectory: core
    ArtifactName: packages
    Artifacts:
    - name: _Specs_.Azure.Core.Basic
      safeName: _Specs_AzureCoreBasic