// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Azure.Core;
using Azure.ResourceManager.Models;
using Azure.ResourceManager.ServiceFabricManagedClusters.Models;

namespace Azure.ResourceManager.ServiceFabricManagedClusters.Models
{
    public static partial class ArmServiceFabricManagedClustersModelFactory
    {
        /// <summary>
        /// [Obsolete] Backward-compatibility shim matching the previous GA factory signature where
        /// <c>skuName</c> was the LAST positional parameter and was <see cref="Nullable{SkuName}"/>.
        /// Forwards to the new factory using the renamed, non-nullable <c>skuKind</c> parameter
        /// (<c>null</c> becomes the default enum value).
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static ServiceFabricManagedClusterData ServiceFabricManagedClusterData(
            ResourceIdentifier id,
            string name,
            ResourceType resourceType,
            SystemData systemData,
            IDictionary<string, string> tags,
            AzureLocation location,
            string dnsName,
            string fqdn,
            System.Net.IPAddress iPv4Address,
            Guid? clusterId,
            ServiceFabricManagedClusterState? clusterState,
            IEnumerable<BinaryData> clusterCertificateThumbprints,
            int? clientConnectionPort,
            int? httpGatewayConnectionPort,
            string adminUserName,
            string adminPassword,
            IEnumerable<ManagedClusterLoadBalancingRule> loadBalancingRules,
            bool? isRdpAccessAllowed,
            IEnumerable<ServiceFabricManagedNetworkSecurityRule> networkSecurityRules,
            IEnumerable<ManagedClusterClientCertificate> clients,
            ManagedClusterAzureActiveDirectory azureActiveDirectory,
            IEnumerable<ClusterFabricSettingsSection> fabricSettings,
            ServiceFabricManagedResourceProvisioningState? provisioningState,
            string clusterCodeVersion,
            ManagedClusterUpgradeMode? clusterUpgradeMode,
            ManagedClusterUpgradeCadence? clusterUpgradeCadence,
            IEnumerable<ManagedClusterAddOnFeature> addOnFeatures,
            bool? isAutoOSUpgradeEnabled,
            bool? hasZoneResiliency,
            bool? isIPv6Enabled,
            string subnetId,
            IEnumerable<ManagedClusterIPTag> ipTags,
            System.Net.IPAddress iPv6Address,
            bool? isServicePublicIPEnabled,
            IEnumerable<ManagedClusterSubnet> auxiliarySubnets,
            IEnumerable<ManagedClusterServiceEndpoint> serviceEndpoints,
            ZonalUpdateMode? zonalUpdateMode,
            bool? useCustomVnet,
            ResourceIdentifier publicIPPrefixId,
            ResourceIdentifier publicIPv6PrefixId,
            ResourceIdentifier ddosProtectionPlanId,
            ManagedClusterUpgradePolicy upgradeDescription,
            int? httpGatewayTokenAuthConnectionPort,
            bool? isHttpGatewayExclusiveAuthModeEnabled,
            AutoGeneratedDomainNameLabelScope? autoGeneratedDomainNameLabelScope,
            int? allocatedOutboundPorts,
            string vmImage,
            bool? enableOutboundOnlyNodeTypes,
            bool? skipManagedNsgAssignment,
            int? maxUnusedVersionsToKeep,
            ETag? etag,
            ServiceFabricManagedClustersSkuName? skuName)
            => ServiceFabricManagedClusterData(
                id: id,
                name: name,
                resourceType: resourceType,
                systemData: systemData,
                tags: tags,
                location: location,
                dnsName: dnsName,
                fqdn: fqdn,
                iPv4Address: iPv4Address,
                clusterId: clusterId,
                clusterState: clusterState,
                clusterCertificateThumbprints: clusterCertificateThumbprints,
                clientConnectionPort: clientConnectionPort,
                httpGatewayConnectionPort: httpGatewayConnectionPort,
                adminUserName: adminUserName,
                adminPassword: adminPassword,
                loadBalancingRules: loadBalancingRules,
                isRdpAccessAllowed: isRdpAccessAllowed,
                networkSecurityRules: networkSecurityRules,
                clients: clients,
                azureActiveDirectory: azureActiveDirectory,
                fabricSettings: fabricSettings,
                provisioningState: provisioningState,
                clusterCodeVersion: clusterCodeVersion,
                clusterUpgradeMode: clusterUpgradeMode,
                clusterUpgradeCadence: clusterUpgradeCadence,
                addOnFeatures: addOnFeatures,
                isAutoOSUpgradeEnabled: isAutoOSUpgradeEnabled,
                hasZoneResiliency: hasZoneResiliency,
                isIPv6Enabled: isIPv6Enabled,
                subnetId: subnetId,
                ipTags: ipTags,
                iPv6Address: iPv6Address,
                isServicePublicIPEnabled: isServicePublicIPEnabled,
                auxiliarySubnets: auxiliarySubnets,
                serviceEndpoints: serviceEndpoints,
                zonalUpdateMode: zonalUpdateMode,
                useCustomVnet: useCustomVnet,
                publicIPPrefixId: publicIPPrefixId,
                publicIPv6PrefixId: publicIPv6PrefixId,
                ddosProtectionPlanId: ddosProtectionPlanId,
                upgradeDescription: upgradeDescription,
                httpGatewayTokenAuthConnectionPort: httpGatewayTokenAuthConnectionPort,
                isHttpGatewayExclusiveAuthModeEnabled: isHttpGatewayExclusiveAuthModeEnabled,
                autoGeneratedDomainNameLabelScope: autoGeneratedDomainNameLabelScope,
                allocatedOutboundPorts: allocatedOutboundPorts,
                vmImage: vmImage,
                enableOutboundOnlyNodeTypes: enableOutboundOnlyNodeTypes,
                skipManagedNsgAssignment: skipManagedNsgAssignment,
                maxUnusedVersionsToKeep: maxUnusedVersionsToKeep,
                etag: etag,
                skuName: skuName);
    }
}
