# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/onlineexperimentation/ci.mgmt.yml
    - sdk/onlineexperimentation/Azure.Analytics.OnlineExperimentation/


extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: onlineexperimentation
    ArtifactName: packages
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.Analytics.OnlineExperimentation
      safeName: AzureAnalyticsOnlineExperimentation
