# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/offazurespringboot/ci.mgmt.yml
    - sdk/offazurespringboot/Azure.ResourceManager.Offazurespringboot/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: offazurespringboot
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.Offazurespringboot
      safeName: AzureResourceManagerOffazurespringboot
